### ISSUE TITLE
unable to start the Open Modelica Compiler

### ISSUE THREAD

**Issue by rsegur** [itesla/PSM#1]
I have this issue while trying to execute a conversion from CIM to Modelica format:
![psm_error](https://user-images.githubusercontent.com/43416381/45803790-b87def00-bcba-11e8-949c-28425cabf9a9.PNG)

OpenModelica is installed and the installation of PSM worked well:
![capturepsmmvnw](https://user-images.githubusercontent.com/43416381/45804145-a05a9f80-bcbb-11e8-85b1-a3662185e08b.PNG)

except for this warning during step 2.2 of the installation process (build and install OpenModelica java integration), the warning appears after "make":
![captureomjava](https://user-images.githubusercontent.com/43416381/45804741-3642fa00-bcbd-11e8-8a3e-cc166ebebe5a.PNG)

Any idea about what is wrong and how to solve this issue?

**Comment by marcosmc** [comment]
We have checked the installation process and found no problems. We also found the same warning seen in your output for step 2.2.

To verify that we can start the OpenModelica Compiler on your environment, can you execute the following instruction on your terminal?
```
$OPENMODELICAHOME/bin/omc` +c=OpenModelica -d=interactiveCorba -g=Modelica
```
The expected result is:
```
Created server.
Dumped Corba IOR in file: </path/file> 
```
Where `/path/file` is a reference to a temporal file.

**Comment by rsegur** [comment]
OK, the problem was coming from the fact that I was using root user:

![captureomc_execution_fail](https://user-images.githubusercontent.com/43416381/46092247-c9e06300-c1b4-11e8-8e56-c3150fbc830c.PNG)

With a regular user, it works!

![image](https://user-images.githubusercontent.com/43416381/46092863-1c6e4f00-c1b6-11e8-8db7-524c583a0f29.png)
